### ISSUE TITLE
iOS: New binding context, new map instance but 2nd map does not properly bind?

### ISSUE THREAD

**Issue by jelmarlaunchlabs** [TorbenK/TK.CustomMap#104]
`public class TestPage:ContentPage
    {
        public TestPage ()
        {
            var controller = new TestModel ();
            this.BindingContext = controller;
            var map = new TKCustomMap ();
            map.SetBinding (TKCustomMap.MapCenterProperty, "center");
            map.SetBinding (TKCustomMap.MapRegionProperty, "region");
            var button = new Button {
                Text = "Go"
            };
            button.Clicked += async (sender, e) => {
                await Navigation.PushModalAsync (new TestPage2 ());
            };
            Content = new StackLayout {
                Children = { 
                    button,map
                }
            };
        }
    }

```
public class TestPage2:ContentPage
{
    public TestPage2 ()
    {
        var controller = new TestModel ();
        this.BindingContext = controller;
        var map = new TKCustomMap ();
        map.SetBinding (TKCustomMap.MapCenterProperty, "center");
        map.SetBinding (TKCustomMap.MapRegionProperty, "region");
        var button = new Button {
            Text = "Go"
        };
        var button2 = new Button {
            Text = "Back"
        };
        button2.Clicked += async (sender, e) => {
            await Navigation.PopModalAsync ();
        };
        button.Clicked += (sender, e) => {
            controller.region = MapSpan.FromCenterAndRadius (new Position (0, 0), Distance.FromMiles (10));
        };
        Content = new StackLayout {
            Children = {
                button,button2,map
            }
        };
    }
}

public class TestModel
{
    public event PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged (string propertyName)
    {
        var ev = this.PropertyChanged;
        if (ev != null) {
            ev (this, new PropertyChangedEventArgs (propertyName));
        }
    }

    private Position _center;
    public Position center {
        get {
            return this._center;
        }
        set {
            if (this._center != value) 
                this._center = value;
            this.OnPropertyChanged ("center");
        }
    }

    private MapSpan _region;
    public MapSpan region {
        get {
            return this._region;
        }
        set {
            if (this._region != value)
                this._region = value;
            this.OnPropertyChanged ("region");
        }
    }
}`
```

changing center in the testpage2 using controller.center = new Position(0,0); does not do anything to the map, but doing this in the first map page works fine.

**Comment by ghost** [comment]
I found that iOS renderer subscribes [https://github.com/TorbenK/TK.CustomMap/blob/master/TK.CustomMap/TK.CustomMap.iOSUnified/TKCustomMapRenderer.cs#L128](url) to MapLoaded event [https://developer.xamarin.com/api/event/MonoTouch.MapKit.MKMapView.MapLoaded/](url). This event will call in case of loading map by underlying os libraries. But due to information, since iOS 4, maps are cached, and whenever an app display a cached map then methods such as "mapViewDidFinishLoadingMap", which is related selector to xamarin event MapLoaded, are not called. It can be solved by using [https://developer.xamarin.com/api/event/MonoTouch.MapKit.MKMapView.DidFinishRenderingMap/](url) first call and proper unsubscribing after first call (because this is event is fired after every dragging, moving or changing map view).

**Comment by TorbenK** [comment]
1.5.1.
