### ISSUE TITLE
Image on pin doesn't stay on the same spot when zooming out

### ISSUE THREAD

**Issue by jamie-steele** [TorbenK/TK.CustomMap#111]
When zooming out with a pin with an Image the pin will move south the more you zoom out on android.

**Comment by MariojosePalma** [comment]
iOS same problem

**Comment by TorbenK** [comment]
Never saw that happening before. You probably need to share some code. Do you use the `Anchor` property?

**Comment by MariojosePalma** [comment]
Yesterday I was playing with the Anchor property.. But I didn't resolved the problem...

For example: on google maps for web, if you have a icon 50x50 pixels and you want the image pin on the center, then you set the anchor property (25,25).

Using TKCustomMap how it should be? I tried using Anchor 25,25 and didn't work, I tried use values between -3 to 3 and didn't work either...

On Aug 18, 2016, at 8:16 AM, TorbenK <notifications@github.com<mailto:notifications@github.com>> wrote:

Never saw that happening before. You probably need to share some code. Do you use the Anchor property?

##

**Comment by TorbenK** [comment]
You dont need so use `Anchor` if you want it to be on the center, that's the default. Anyway, you can read here how to set the anchor point correctly:

https://developers.google.com/android/reference/com/google/android/gms/maps/model/Marker.html#setAnchor(float, float)

But this is probably irrelevant for this issue.

**Comment by MariojosePalma** [comment]
I'll try the solution of the following issue: https://github.com/TorbenK/TK.CustomMap/issues/114
If this works then I we can close it.

**Comment by TorbenK** [comment]
Still not sure how this is relevant for this specific issue

**Comment by MariojosePalma** [comment]
Let me explain a little bit:

If the anchor is not the center of the image, then  when you zoom out or rotate the map, the image looks like is moving in the map... 
![image](https://cloud.githubusercontent.com/assets/5280610/17778968/f8684a74-6533-11e6-8130-2cfe99a9e4b8.png)

for example I'm using a image like that one... a boat... and the idea is that the anchor always stay in the center of the boat... right now the anchor maybe is 0,0 (top, left) and when you Zoom out you feel like the boat is moving more to south... because the anchor is 0,0... If we could set the anchor on the midle of the image... then the image will never move from the center position.

**Comment by TorbenK** [comment]
Did that fix the issue?

**Comment by MariojosePalma** [comment]
Well, this is working for me using 
`pin.Anchor = new Point(0.5, 1)`
For some reason that is the center
