### ISSUE TITLE
MapRegion binding works only the very first time

### ISSUE THREAD

**Issue by Haukinger** [TorbenK/TK.CustomMap#124]
I'm on android and I bind MapRegion and Polylines to properties on my view model. When I update those properties and trigger their respective PropertyChanged, the map shows the polyline. But only the very first polyline has the correct viewport set. Each subsequent polyline gets the same too much zoomed in zoomlevel, but it seems the center is correct. If I show a different polyline as the first one, that is displayed correctly, so the data itself is correct.

Any idea what I'm doing wrong?

**Comment by TorbenK** [comment]
Can you make a video or provide an example? Not sure if I understand correctly.

**Comment by Haukinger** [comment]
This seems to be a problem with the xamarin forms map. I've implemented my own custom map with bindable route property, and I see the exact opposite behavior: the first time I show the map, the zoom is wrong, but all subsequently shown routes correctly adjust the zoom.

**Comment by TorbenK** [comment]
1.5.1.

**Comment by frode** [comment]
I've looked through the changes that was made for 1.5.1, and can't see any changes that should affect the behaviour @Haukinger mention. Do you remember what changes that affected this @TorbenK ?
The reason I ask is because i'm using a custom renderer and a custom map where I experience the exact same scenario. Initial zoom level is wrong, subsequent ones are correct.. Map radius property is bound to a view model.
