### ISSUE TITLE
Crash Map MasterDetail Page - iOS

### ISSUE THREAD

**Issue by andreluiz1987** [TorbenK/TK.CustomMap#161]
Hi!

My application is presenting a curious error.
I'm working with the MasterDetail Menu, I have two pages with maps, and in one I allow the user to change their location through the DragEndCommand. When I perform this DragEnd function and try to go through the Menu to another screen, the application closes without giving any exceptions.
By analyzing the logs I noticed that it has something related to the TaskAwaiter class.
I am not sure what this means but if in case anyone is interested in helping me I will post the complete error log.
The only thing that comes to my mind is that something like this is occurring when trying to change the screen crash.

**Comment by JeanCollas** [comment]
I would recommend to use the same map instance for both: create a static "map" object and add it to the relevant page when it appears.
I had an issue with a tabbedpage, as it recreates a new map every time you change tabs (when you click on the next-next tab, then back to the map)

**Comment by JeanCollas** [comment]
Have a look at the last post: https://github.com/TorbenK/TK.CustomMap/issues/146 
You should do this and the "unregister" on parent change.

**Comment by jfversluis** [comment]
I hope @JeanCollas comment has done anything for you.
Also with these kind of errors it can be very helpful (for yourself as well as for us to create a small sample project which indicates the problem. You could even add the source code from here and debug it yourself if that is something you would want to do and provide us with a fix.

Could you at least post the full log?

**Comment by JeanCollas** [comment]
I guess you are developing using Visual Studio. 
You could try "CTRL + ALT + E", then check the box for all Common Language Runtime Exceptions and start in debug mode. This may help you to understand the issue. But of course you should work with the map sources, not the nugget package, or at least just include the sources in your solution (and ideally with the Xamarin.Forms source projects also included in the solution, so that the debugger can follow the exception in the code).
If it is not an stack overflow exception, you should be able to find the issue.

**Comment by andreluiz1987** [comment]
Thanks for replying @JeanCollas , @jfversluis , I'll follow your suggestions.

**Comment by andreluiz1987** [comment]
@jfversluis http://pastebin.com/7GYLRX7h
But one thing, the error only occurs when I use DrangEnd. When I do not use change of screen without problems.

**Comment by TorbenK** [comment]
1.5.1
