### ISSUE TITLE
iOS pin strange behavior/crash

### ISSUE THREAD

**Issue by feliperugai** [TorbenK/TK.CustomMap#185]
Hi there,

The issue was closed after the 1.5.1 update but it still causing the same error.
I commented on issue #159 but got no answers. I don't know if people receive notifications about an closed issue on Github , so I'm opening another one.
In #159 I provided a sample code analyzed by @TorbenK and he commented that it was fixed in 1.5.1, but I couldn't notice any changes.

Any support will be highly appreciated!
Thank you!

**Comment by TorbenK** [comment]
@felrugai 

So this turned out to be very strange. On the simulator the MonoTouch exported function `_original_setCoordinate` is called when dragging completes. 

If you deploy to a device, `SetCoordinate` is called instead. It also seems that it automatically adds an observer, so calling `WillChangeValue`, `DidChangeValue` adds a second one which causes the crash. 

Please check if everyhting works now. I only ran a very simple, quick tests myself. If everyhting is fine I will generate a new NuGet package asap.

**Comment by feliperugai** [comment]
@TorbenK 
Hi there!
I was starting to change this specific part and received this message.
Great news! It's not crashing anymore, and my polygon is now rendering as it should!
In some cases it's confusing itself with draggable pins, but the crash problem is definately gone!
Thank you,  your project is really awesome! Congratz!

**Comment by TorbenK** [comment]
> In some cases it's confusing itself with draggable pins, but the crash problem is definately gone!

What do you mean by that? Is that a problem I should look at?

**Comment by feliperugai** [comment]
Actually, I think it's my mistake. I'll try some changes and get back to you
