### ISSUE TITLE
1.5.2-pre1

### ISSUE THREAD

**Issue by TorbenK** [TorbenK/TK.CustomMap#202]
I just release a pre release for 1.5.2. I will release a new stable release as soon as Xamarin updates its bindings for Android. It is still targeting `Xamarin.GooglePlayServices.Maps` with a hard dependency on `29.0.0.1` currently. 

If your bugs are fixed, please close them. 

There will be a pre release of 2.0.0 soon, which will include UWP support. Thanks to @jfversluis for his work on that.

**Comment by kikolopes90** [comment]
I already tested new updates Xamarin Forms Maps 2.3.4.224, it is not working.

It will be because of this?
https://github.com/xamarin/Xamarin.Forms/tree/master/Xamarin.Forms.Maps.Android

Tested v1.5.1 or v1.5.2-pre1:
XFM 2.3.4.224 does not work well.
XFM 2.3.4.214-pre6 does not work well.
XFM 2.3.4.214-pre5 works fine.
