### ISSUE TITLE
UIKit.UIGestureRecognizer.Dispose crash after loading a map page for the second time

### ISSUE THREAD

**Issue by pamela032709** [TorbenK/TK.CustomMap#364]
The Map crash after opening the page for the second time.
Crash info 

> UIGestureRecognizer+<>c__DisplayClass4_0.<OnDispose>b__0

 () /Library/Frameworks/Xamarin.iOS.framework/Versions/12.8.0.0/src/Xamarin.iOS/UIKit/UIGestureRecognizer.cs:48
NSAsyncActionDispatcher.Apply () /Library/Frameworks/Xamarin.iOS.framework/Versions/12.8.0.0/src/Xamarin.iOS/Foundation/NSAction.cs:152
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) /Library/Frameworks/Xamarin.iOS.framework/Versions/12.8.0.0/src/Xamarin.iOS/UIKit/UIApplication.cs:79
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) /Library/Frameworks/Xamarin.iOS.framework/Versions/12.8.0.0/src/Xamarin.iOS/UIKit/UIApplication.cs:63

> 
To run the sample [https://github.com/pamela032709/custommapscrash](url)

to see the working version please refer to this post [https://github.com/xamarin/xamarin-macios/issues/5899#issuecomment-483641416](url)

**Comment by busec0** [comment]
duplicate of https://github.com/TorbenK/TK.CustomMap/issues/363

**Comment by pamela032709** [comment]
that occurs on a renderer page, mine happens on xamarin forms without any
render or pushing a page on the stack. similar but not a duplicate. in the
rendered page you can easily manipulate ONDispose()  function. However, on
Xmarin forms, it crashes it the main of the whole app. so there is not fix
on my end.

**Comment by CarlosICarrillo** [comment]
Yes. I have the same issue. Thanks for any help.

**Comment by busec0** [comment]
@pamela032709 Nope, it is happening on a simple XF app using a plain TK.CustomMap as well. 

The custom renderer I provided in the sample app is copied entirely from https://github.com/TorbenK/TK.CustomMap/blob/Development/Source/TK.CustomMap.iOSUnified/TKCustomMapRenderer.cs and it has the call to `base.Dispose()` commented out to prove it won't crash without that, emphasising where the problem is. Please check the sample app I provided. 

It is the same bug as it occurs while `disposing` the TKCustomMap, even though: 

* it happens while `popping` a page (aka removing it from the navigation stack)
* It happens when changing the page as you do with the master-detail.  

In both cases the Page containing the Map will get Disposed. Same bug, different scenarios, both leading to a `disposed` TK.CustomMap View.

**Comment by pamela032709** [comment]
Yup - you are right.

**Comment by pamela032709** [comment]
This issue gets fixed with the new xamarin.forms.ios 12.8
