### ISSUE TITLE
PinSelectedCommand no executing when pin is selected?

### ISSUE THREAD

**Issue by Alpha-Rome0** [TorbenK/TK.CustomMap#99]
According to the same code, it looks like the map should center itself when a pin is selected but its not. I tried implementing in my app as well and that command is not getting executing when a pin is selected.

**Comment by TorbenK** [comment]
I think this is due to missing command parameter.

**Comment by Alpha-Rome0** [comment]
Can you please elaborate? What should the command look like?

**Comment by JeanCollas** [comment]
Check my answer on this topic:
https://github.com/TorbenK/TK.CustomMap/issues/75

**Comment by Alpha-Rome0** [comment]
thanks that fixes the issue. Perhaps the sample code should be updated to reflect these changes.

**Comment by vincentcastagna** [comment]
Hello,

I know this issue is closed but I can't get it work too ... Well, when I use first possibility with mapcenter it works, but only ONCE and the animation is ugly ... And others possibilities do not work, I get a null exception. What am I doing wrong ? 

I'm not using any XAML, but I've got a null exception ...

` _customMap.SetBinding(TKCustomMap.PinSelectedCommandProperty, "PinSelectedCommand");`
//

And in my MapViewModel : 

    /// <summary>
        /// Pin Selected bound to the <see cref="CustomMap"/>
        /// </summary>
        public Command PinSelectedCommand
        {
            get
            {
               return new Command<CustomPin>((CustomPin pin) =>
                {
                    // Chose one

                    // 1. First possibility
                    this.MapCenter = this.SelectedPin.Position;
                    // 2. Possibility
                    //this.MapRegion = MapSpan.FromCenterAndRadius(this.SelectedPin.Position, this.MapRegion.Radius);
                    // 3. Possibility
                    //this.MapFunctions.MoveToMapRegion(
                    //    MapSpan.FromCenterAndRadius(this.SelectedPin.Position, Distance.FromMeters(this.MapRegion.Radius.Meters)),
                    //    true);
                });
            }
        }
